### ISSUE TITLE
Source Code request

### ISSUE THREAD

**Issue by DanielChantlos** [Esri/AuGeo#14]
This is a great application, thanks for creating this.
Is there any possibility you could post the AuGeo source code here on GitHub? I have an AuGeo app created, but my team has several customization requests for me to work on. In order for me to complete these requests, I will need the source code.

Thanks again!
-Daniel

**Comment by JohnHasthorpe** [comment]
Hi @DanielChantlos - are you aware of the fact the the app is available as an AppStudio template?
If you download it as an Enterprise template in the AppStudio, you can view the source code.
