### ISSUE TITLE
Image Url's are not displaying images in the Augeo Pop-up

### ISSUE THREAD

**Issue by ronaldsheaks** [Esri/AuGeo#22]
Hi, this is a really cool app I have been experimenting with since it's release. I created a window in AuGeo that displayed tree data before https://youtu.be/iEZBek_F0_o and now it seems that when I try to replicate this project the image url's do not display the photos. It seems as if adding photo url's also causes the app to behave strangely, only showing distance from a feature and no other pop-up data. 

I have tried to add a simple one word description field, and this only seems to work (shows the one word description - PlantOne, PlantTwo, etc. in the AuGeo Pop-up) a small portion of the time.

I will go through the code in the appstudio qtcreator and see if I find anything that may resolve these issues and call technical support.

This app is really cool and I think that it is the future of mapping.

Thank You

**Comment by dominikargast** [comment]
Hi @ronaldsheaks, thanks for your kind words. I have not encountered any issues in displaying images in the pop-up. Have you checked that the settings are correct? Make sure that the "Media" checkbox is ticked in the Settings->Popup Settings panel.

<img width="999" alt="Screen Shot 2019-12-19 at 09 41 45" src="https://user-images.githubusercontent.com/25575734/71129541-c9157000-2243-11ea-9bcc-428f4cceffce.png">

**Comment by ronaldsheaks** [comment]
Hi Dominik,

That was it, wow I was wayyy off. I'll delete the issue from Github. I
appreciate the quick response, I am relieved that it was something so
simple. I've got some plans in the works for developing apps with AuGeo so
hopefully we cross paths again.

Thank You!

Ron

**Comment by dominikargast** [comment]
@ronaldsheaks Good to hear. Happy coding!
