### ISSUE TITLE
AuGeo - are there any news?

### ISSUE THREAD

**Issue by holubvl3** [Esri/AuGeo#23]
Dear all, 

I am seekeing for any information, what is the current status, or roadmap/future for AuGeo. We have few customers, who seems to be interested in using AuGeo. 

Is there any future of this app, or htere will be another augmented reality app build on Quartz Runtime?

The last information here is from October 2019 from @dominikargast. Is there any change? 

Thank you for any response.

Regards,

Vldimir

**Comment by dominikargast** [comment]
@holubvl3 Thanks for your continued interest. Unfortunately, further work on AuGeo is currently not included in our development plan.

**Comment by holubvl3** [comment]
Dear @dominikargast, 

thank you for response and clarification. Could you give me any recommendation, what we should recommend to our customer who wants to use Augmented reality with Esri? Build custom app with Quartz or Build the App with AuGeo template in AppStudio?

Thank you.

**Comment by esoekianto** [comment]
Both options are good. This is depending on the requirements of the app you are going to build. ArcGIS Runtime has Augmented Reality capability added in the last release, and the AuGeo source code will continue to be available in AppStudio Desktop for our customers to customize and make it your own app.

**Comment by holubvl3** [comment]
Dear @esoekianto, thank you very much for clarification. Anyway it would be great to have it here Esri augmented reality app (like AuGeo was). We are getting more and more questions about it, also I found an Idea about it: https://community.esri.com/ideas/16884-augmented-reality-application, so I am not alone with such request.

**Comment by holubvl3** [comment]
Dear @dominikargast, Dear @esoekianto, I made another idea, about the future of Augmented reality in Esri, which would be great if you can consider it. 

https://community.esri.com/ideas/17974-augmented-reality-in-esri-products-native-app-or-web-app

Thank you.

**Comment by esoekianto** [comment]
Thank you for submitting the idea, I am sure our product management team is looking at all of the ideas very closely.

**Comment by holubvl3** [comment]
Dear @esoekianto,

it would be great to have AR in Esri apps again! 

Have a great day.
