### ISSUE TITLE
Is AuGeo source code available in 4.2 release of AppStudio?

### ISSUE THREAD

**Issue by previewqueen** [Esri/AuGeo#24]
I have upgraded my AppStudio Developer Edition to the most recent release of 4.2, however, I can no longer seem to get access to the AuGeo template any more.
Is it available in the 4.2 release, or am I missing something?
Thanks!

**Comment by dominikargast** [comment]
Hi @previewqueen, the AuGeo source code can be downloaded from inside AppStudio. Go to "New App" -> "Enterprise" -> "AuGeo".
