### ISSUE TITLE
Camera inverted on Nexus 5x running Android 7.1

### ISSUE THREAD

**Issue by geompc** [Esri/AuGeo#5]
Upgraded to Android 7.1 recently and afterwards the the camera view in AuGeo is inverted on the Nexus 5x. [Possible solution](https://groups.google.com/forum/#!topic/zxing/JqIGVBUXup0)?

**Comment by spatialdude** [comment]
Thank @geompc 

We're investigating the matter.

**Comment by JohnHasthorpe** [comment]
Internal issue: https://devtopia.esri.com/Melbourne/Horizon/issues/177

**Comment by JohnHasthorpe** [comment]
Verified and closed. Fix will be available in the next release.
